print("Enter the employee name: ")
name = input()
print("Enter the employee age: ")
age = int(input())
print("Enter the employee salary: ")
salary = float(input())
print("Enter the gender of the employee")
gender = Input()
print("Employee Name: ", name)
print("Employee Age: ", age)
print("Employee Salary: ", salary)
print("Employee's gender", gender)