print("Enter your name: ")
name = input()
print("Enter roll no: " )
roll = int(input())
print("Enter marks:")
marks = float(input())
print(" My Name: ", name)
print("My Roll No: ", roll)
print("My Marks: ", marks)
